version: '3.8'

services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: "npm install && npm run build && npx serve -s build"
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html
    restart: always
