name: Deploy to TechnoWizzard Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy on Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Deploy and Build
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/miniwizzard/miniwizzard/apps/portfolio
            git pull origin main
            npm install
            npm run build
            docker-compose down
            docker-compose up -d --build
